# Generated by Django 3.0 on 2020-08-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='userId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
