# Generated by Django 3.0 on 2020-08-13 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200812_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='userId',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='userId',
            new_name='user_id',
        ),
    ]
