# Generated by Django 3.0 on 2020-08-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200813_0040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseType',
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[(0, 'Housing'), (1, 'Groceries'), (2, 'Gas'), (3, 'Self care'), (4, 'Leisure'), (5, 'Debts'), (6, 'Utility'), (7, 'Gifts')], default=(0, 'Housing'), max_length=10),
        ),
    ]
