# Generated by Django 3.0 on 2020-08-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200813_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('Housing', 'Housing'), ('Groceries', 'Groceries'), ('Gas', 'Gas'), ('Self care', 'Self care'), ('Leisure', 'Leisure'), ('Debts', 'Debts'), ('Utility', 'Utility'), ('Gifts', 'Gifts')], default=('Housing', 'Housing'), max_length=10),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
